# Generated by Django 5.2.10 on 2026-01-20 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="last_payment_attempt",
            field=models.DateTimeField(
                blank=True, help_text="Last failed PIN attempt", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of failed PIN attempts"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_confirmed_at",
            field=models.DateTimeField(
                blank=True, help_text="When payment was confirmed via PIN", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_pin",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="6-digit verification PIN generated by support",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_pin_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the PIN expires (24 hours after generation)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_pin_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the PIN was generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Support staff who verified the payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("ZELLE", "Zelle"),
                    ("PAYPAL", "PayPal"),
                    ("CASHAPP", "Cash App"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_pin"], name="shop_order_payment_ac2321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status", "status"],
                name="shop_order_payment_10abd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="shop_order_user_id_042042_idx"
            ),
        ),
    ]
