# Generated by Django 6.1 on 2026-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_orderitem_options_alter_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
